#!/bin/bash
#
# Munin plugin for monitoring time of returning a webpage.
#
#%# family=auto
#%# capabilities=autoconf

URL=${url:-"google.com"}

# some shells (e.g., bash(1)) have a built-in time commandthat provides less
# functionality. You may need to specify command pathname.
TIME="/usr/bin/time -f %e"
WGET="/usr/bin/wget -q -O /dev/null -t 1 -T 10"

function config {
    cat << EOF
graph_title Web response
graph_vlabel seconds
seconds.label Seconds
EOF
}

function check_dns {
    host "$1" > /dev/null 2>&1
    return $?
}

if [ "$1" == "autoconfig" ] ; then
    echo "yes"
    exit 0
fi

if [ "$1" == "config" ] ; then
    config
    exit 0
fi


check_dns $URL || exit -1
time=$(($TIME $WGET $URL) 2>&1 )
echo "seconds.value $time"
